### ISSUE TITLE
Feature request: get original error from ExceptionCustom

### ISSUE THREAD

**Issue by Nogias9x** [kanekotic/express-exception-handler#5]
First, thank you for this amazing module. It's helpful and easy to use.

But in some cases, I need the origin error which is not included in our `ExceptionCustom`.
I think we may add it like this:
```
class ExceptionCustom extends Error {
    constructor (message, status, response) {
        super(message || 'Unknown Exception')
        if (message instanceof Error) {
            this.stack = message.stack
        } else {
            Error.captureStackTrace(this, this.constructor)
        }
        this.name = this.constructor.name
        this.status = status || 500
        this.response = response
+       this.originError = message
    }
}

module.exports = ExceptionCustom
```
If you are OK with it, I can make a PR for it.
Thank you and have a nice day.

**Comment by kanekotic** [comment]
Sorry for not answering earlier. So can you elaborate more on this please? orginError is part of the response body you are expecting?

**Comment by Nogias9x** [comment]
Thank you for your kind and detailed response @kanekotic . I really appreciate your time and help.

Regarding to the `ExceptionCustom`,  I understand that it already had useful `message`, `stack` and `response`. But the `message` is a short brief to display, and `stack` is for debugging, and `response` is passed from outside of the  `ExceptionCustom`. What I need is the origin error's information (as how we need error stack).

In my case, I'm using Joi (validation module) and Sequelize (ORM). Their exceptions contain a lot of useful information that I need to display (but their message is very short and not too friendly). 
For a simple example, If users register with a taken username, I need to display "Username must be unique." (Sequelize's exceptions contain info for that), but the exception's message is kind of "SequelizeUniqueConstraintError: Constraint violation"

My fast work-around is add `originError` into  `custom-exception.js`, overwrite it on corresponding file in node_module when executing `docker-compose`:
```
// custom-exception.js
class ExceptionCustom extends Error {
  constructor (message, status, response) {
    super(message || 'Unknown Exception');
    if (message instanceof Error) {
      this.stack = message.stack;
    } else {
      Error.captureStackTrace(this, this.constructor);
    }
    this.name = this.constructor.name;
    this.status = status || 500;
    this.response = response;
+   this.originError = message;
  }
}

module.exports = ExceptionCustom;
```

Could you please consider about this usecase?

Thank you and have a nice day :)

**Comment by Nogias9x** [comment]
Hi @kanekotic,
Could you please take a look at it?

**Comment by kanekotic** [comment]
yes I will give me like 1 day because it has been hectic at work :)

**Comment by Nogias9x** [comment]
Oh, no worries, please.
I'm glad that you think it makes senses.
If I could help anything, please let me know.

Thank you @kanekotic

**Comment by kanekotic** [comment]
🙏 Sorry For this felt out of my radar I will try to work on it this week 🙏

**Comment by Nogias9x** [comment]
Very kind you are @kanekotic . Thank you so much <3

**Comment by kanekotic** [comment]
done. deployed as `1.3.0`

**Comment by kanekotic** [comment]
@all-contributors please add @Nogias9x for ideas
