### ISSUE TITLE
Feature Request: run `res.json` by default when the internally returned value is an object

### ISSUE THREAD

**Issue by ozomer** [kanekotic/express-exception-handler#6]
This feature could be applied by calling `exceptionHandler.handle({ defaultJsonResponse: true })` and if the internal handler returns a value (or a successful promise to a value), and this value is an object (not a primitive), it should try calling `res.json(...)` on this value.
If the value is a primitive, maybe `res.end()` should be called.
The current behavior of express where the connection just "hangs" is annoying.

This should be applied only to handlers that accept exactly two arguments `req` and `res` (i.e. `fn.length == 2`).
If the function accepts 3 or more parameters (i.e. the `next` callback function), this could be a special case and the user may not want this package to call `res.json` by its own. In many legacy code, developers handle errors by calling `return next(new Error(...));` - the `return` call here is just to end the handler execution, not something that we would want to return to the user.

Also, It should also be checked that `res.headersSent` is still false. If it's true it means the internal handler already started responding to the client, and we should not call `res.json()` or `res.end()`.

Maybe this package should be forked to allow more features than just exception-handling. *express-improved-handler* could be a nice name. *express-async-handler* is already taken, and besides this project does not apply only to async functions.

**Comment by ozomer** [comment]
Are you considering to to create `express-improved-handler`? Or do you think it would be better to implement it in the current name?
If you want to keep express-exception-handler minimalist and not add features that are not related to exceptions, I understand. Do you mind if I fork your package and create `express-improved-handler` myself? (Well, the license is MIT but I'm still asking out of politeness).

**Comment by kanekotic** [comment]
well I am not expecting this library to be minimalistic so feel free to add some of the improvements you feel are good. I think your ideas are interesting.
