### ISSUE TITLE
Feature Request: Make sure that `next` is not called twice

### ISSUE THREAD

**Issue by ozomer** [kanekotic/express-exception-handler#7]
I've noticed [here](https://github.com/kanekotic/express-exception-handler/blob/master/lib/handle.js#L8) that the wrapper also applies to functions that receive 3 parameters: `req`, `res` and also `next`.
This means that the `next` callback could unexpectedly be called twice - once by the user, and once by an error thrown later or a promise-rejection.

This protection could be applied by calling `exceptionHandler.handle({ nextOnce: true })`.

**Comment by kanekotic** [comment]
HEllo @ozomer I will have a look in both of the request and try to see what i can do. Also feel free to add a PR if you feel confortable
